"""Line-count gate + ledger generator for AdaRag.

Enforces the ~300-line soft ceiling from CONVENTIONS.md: walks the project's source files,
flags any that warn (>= WARN) or exceed the hard cap (> limit), and refreshes the
auto-generated ledger block in CONVENTIONS.md. Exits non-zero when a non-exempt file is over
its cap, so it doubles as a pre-commit / CI gate.

Usage:
    uv run python scripts/check_lines.py            # write ledger + report, gate on violations
    uv run python scripts/check_lines.py --check    # report + gate only, don't touch the ledger
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

# --- policy (keep in sync with CONVENTIONS.md) -------------------------------
WARN = 250  # refactor soon
HARD = 300  # split before moving on
TEST_HARD = 400  # tests get more room

SOURCE_EXTS = {".py", ".ts", ".tsx", ".js", ".jsx", ".vue", ".svelte"}
SKIP_DIRS = {
    ".git",
    ".venv",
    "__pycache__",
    "node_modules",
    ".ruff_cache",
    ".pytest_cache",
    ".mypy_cache",
    "hf_cache",
    ".huggingface",
    "qdrant_storage",
    "pg_data",
    ".next",
    "out",
    "dist",
    "build",
}
# Files matched here are listed but never gated (auto-generated / vendored).
EXEMPT_SUFFIXES = ("_pb2.py",)

LEDGER_START = "<!-- LEDGER:START"
LEDGER_END = "<!-- LEDGER:END -->"

ROOT = Path(__file__).resolve().parent.parent
CONVENTIONS = ROOT / "CONVENTIONS.md"


@dataclass
class Entry:
    path: str
    lines: int
    limit: int
    exempt: bool

    @property
    def status(self) -> str:
        if self.exempt:
            return "exempt"
        if self.lines > self.limit:
            return "OVER"
        if self.lines >= WARN:
            return "warn"
        return "ok"


def is_test(path: Path) -> bool:
    return path.name.startswith("test_") or path.name.endswith("_test.py") or "tests" in path.parts


def count_lines(path: Path) -> int:
    try:
        return len(path.read_text(encoding="utf-8").splitlines())
    except (UnicodeDecodeError, OSError):
        return 0


def collect(root: Path) -> list[Entry]:
    entries: list[Entry] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file() or path.suffix not in SOURCE_EXTS:
            continue
        rel_parts = path.relative_to(root).parts
        if any(part in SKIP_DIRS for part in rel_parts):
            continue
        rel = path.relative_to(root).as_posix()
        limit = TEST_HARD if is_test(path) else HARD
        entries.append(Entry(rel, count_lines(path), limit, rel.endswith(EXEMPT_SUFFIXES)))
    return entries


def render_ledger(entries: list[Entry]) -> str:
    rows = sorted(entries, key=lambda e: e.lines, reverse=True)
    badge = {"ok": "ok", "warn": "warn", "OVER": "OVER", "exempt": "exempt"}
    out = [
        f"{LEDGER_START} — generated by scripts/check_lines.py; do not edit by hand -->",
        "",
        f"_{len(rows)} source files - soft ceiling {HARD} (warn {WARN}, tests {TEST_HARD})._",
        "",
        "| File | Lines | Limit | Status |",
        "| --- | ---: | ---: | --- |",
    ]
    out += [f"| `{e.path}` | {e.lines} | {e.limit} | {badge[e.status]} |" for e in rows]
    out += ["", LEDGER_END]
    return "\n".join(out)


def write_ledger(text: str) -> None:
    doc = CONVENTIONS.read_text(encoding="utf-8")
    start, end = doc.find(LEDGER_START), doc.find(LEDGER_END)
    if start == -1 or end == -1:
        raise SystemExit("CONVENTIONS.md is missing the LEDGER markers.")
    CONVENTIONS.write_text(doc[:start] + text + doc[end + len(LEDGER_END) :], encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description="Line-count gate + ledger for AdaRag.")
    parser.add_argument("--check", action="store_true", help="gate only; don't write the ledger")
    args = parser.parse_args()

    entries = collect(ROOT)
    over = [e for e in entries if e.status == "OVER"]
    warn = [e for e in entries if e.status == "warn"]

    if not args.check:
        write_ledger(render_ledger(entries))
        print(f"Ledger updated in {CONVENTIONS.name} ({len(entries)} source files).")

    for e in warn:
        print(f"  warn  {e.path}: {e.lines} lines (>= {WARN})")

    if over:
        for e in over:
            print(f"  OVER  {e.path}: {e.lines} lines (> {e.limit})", file=sys.stderr)
        # Exit 2 so a PostToolUse hook feeds this back to Claude as a blocking reason.
        print(
            f"{len(over)} file(s) over the {HARD}-line ceiling. Split before continuing.",
            file=sys.stderr,
        )
        return 2
    tail = f" ({len(warn)} approaching)." if warn else "."
    print(f"All {len(entries)} source files within limits{tail}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
